### PR TITLE
feat: Adds a new feature - create delete source endpointx

### PR DESCRIPTION
**Pull request by NagarajNidagundi**

### CODE REVIEW

**Comment by AmitkumarEvry** [comment]
looks good.

**Comment by ChetanaRK** [comment]
Looks good.

**Comment by davidw-foxtrax** [comment]
@NagarajNidagundi Does this branch actually depend on tel-84, or can it be pointed directly to master?

Either way, can you please rebase it with the latest updates?  Thanks.

**Comment by NagarajNidagundi** [comment]
Created a new branch and requesting to merge. So closing this PR.

**Pull request closed without merging**
