### PR TITLE
Tel 86 create get tenant sources endpoint

### PR DESCRIPTION
**Pull request by NagarajNidagundi**

### CODE REVIEW

**Comment by WW-CICD** [comment]
### AWS CodeBuild CI Report

* CodeBuild project: pr-CodeBuild-WWTelematicsSourceService-CodeBuildProject
* Commit ID: 191bd439511db2fa5033b48d0789c3abc87b8523
* Result: FAILED
* [Build Logs](https://9lxt94z6ka.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=df9a9f42-3128-4ce3-992d-c48e3feb9028%2Fbuild.log) (available for 10 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Comment by ChetanaRK** [comment]
@NagarajNidagundi - Looks good.

**Comment by AmitkumarEvry** [comment]
Looks good

**Comment by davidw-foxtrax** [comment]
Replaced by #20

**Pull request closed without merging**
